# docker-compose up -V -d
services:
  database:
    build:
      context: .
      dockerfile: mongodockerfile
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - "database"
      - "redis"
  redis:
    image: redis:latest
    hostname: 'redis-serv'
